version: '3'

services:
  db:
    image: postgres
    ports:
    - 6543:5432
    environment:
      POSTGRES_DB: credhub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  credhub:
    build: .
    image: credhub
    depends_on: [db]
    links:
      - db
    ports:
    - 9000:9000
    environment:
      DATABASE: postgres
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      DATABASE_URL: jdbc:postgresql://db:5432/credhub?autoReconnect=true
