security:
  oauth2:
    resource:
      id: credhub
  authorization:
    acls:
      enabled: false

spring:
  jpa:
    hibernate:
      ddl-auto: validate
  main:
    allow-bean-definition-overriding: true
